#
# test-kitchen using kitchen-dokken
#
# to use this instead of Vagrant, use:
#
#   $ KITCHEN_LOCAL_YAML=.kitchen.dokken.yml kitchen verify
#
driver:
  name: dokken
  privileged: true # because Docker and SystemD/Upstart
  chef_version: 12.21.3

transport:
  name: dokken

provisioner:
  name: dokken
  # chef_log_level: debug

platforms:
- name: debian-9
  driver:
    image: dokken/debian-9
    pid_one_command: /bin/systemd

- name: debian-8
  driver:
    image: dokken/debian-8
    pid_one_command: /bin/systemd


# suites are taken from .kitchen.yml usually
# suites:
