---
driver:
  name: vagrant

verifier:
  name: inspec

provisioner:
  name: chef_zero

platforms:
  - name: debian-8.11
  - name: debian-9.9

suites:
  - name: default
    run_list:
      - recipe[site-dockertypo3org::default]
    attributes:
